### ISSUE TITLE
Such a good project, why not update

### ISSUE THREAD

**Issue by daxiondi** [misi/codelab#3]

**Comment by misi** [comment]
@daxiondi 
The reason is simple: Unfortunately I have no time for it. :-/ 

I try to split my time between multiple open source projects. e.g. coturn and edumeet, ..

**Comment by daxiondi** [comment]
That's too bad. 
Can you share Google doc with me? 
I have time to contribute to this project

**Comment by misi** [comment]
Sure.
The doc is in odf in the https://github.com/misi/codelab/blob/master/source/webrtc-c0d3l4b.odt
You can edit if you upload.
Or if you want to access my instance please send me your google id or email and I invite you to it.

**Comment by daxiondi** [comment]
That's great, 
my Gmail email 
`theasura154@gmail.com` By the way,
 I'm also studying coturn recently. 
We can communicate with each other
